version: '3.4'

services:
  platformservice:
    image: mohsenasadi5011/platformservice
    ports:
     - 2020:80
    depends_on:
          - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"

    environment:
        SA_PASSWORD: "qwerty@123"
        ACCEPT_EULA: "Y" 
